import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../components/navbar';
import { AuthProvider } from './auth-context';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Note Taking App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} bg-neutral-50 dark:bg-zinc-900 min-h-[calc(100vh-65px)]`}
      >
        <AuthProvider>
          <Providers>
            <Navbar />
            <main className="main mt-[65px] h-full ">{children}</main>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
